version: "3.9"
services:
  service:
    build: .
    links:
      - database
    depends_on:
      - database
    env_file:
      - database.docker.env
    ports:
      - "80:80"
      - "8080:8080"
  database:
    hostname: database
    image: "postgres:13.2-alpine"
    env_file:
      - database.docker.env
    ports:
      - "5432:5432"