spring:
  datasource:
    url: jdbc:tc:postgresql:13.2:///test_database
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true